---
- name: Configure Palo Alto Firewall
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Configure interfaces
      panos_interface:
        provider:
          ip_address: "192.168.1.1"  # Replace with your firewall's management IP
          api_key: "YOUR_API_KEY"   # Replace with your valid API key
        name: "{{ item.name }}"
        mode: "layer3"
        ip: "{{ item.ip }}"
        dhcp_client:
          enable: "{{ item.dhcp }}"
          create_default_route: false
      loop:
        - { name: "ethernet1/1", ip: null, dhcp: true }
        - { name: "ethernet1/2", ip: null, dhcp: true }
        - { name: "ethernet1/3", ip: null, dhcp: true }
        - { name: "ethernet1/4", ip: null, dhcp: true }

    - name: Add virtual routers
      panos_virtual_router:
        provider:
          ip_address: "192.168.1.1"
          api_key: "YOUR_API_KEY"
        name: "{{ item }}"
      loop:
        - "trust"
        - "untrust"
        - "vpn"
        - "webtier"

    - name: Set firewall hostname
      panos_device:
        provider:
          ip_address: "192.168.1.1"  # Default management IP
          api_key: "YOUR_API_KEY"   # Replace with your valid API key
        hostname: "PANFW01"         # Default hostname

    - name: Add security policy
      panos_security_rule:
        provider:
          ip_address: "192.168.1.1"
          api_key: "YOUR_API_KEY"
        rule_name: "POC_Any_Any_premigrate"
        from_zone: ["any"]
        to_zone: ["any"]
        source: ["any"]
        destination: ["any"]
        application: ["any"]
        service: ["any"]
        action: "allow"
        tag: ["POC-DELETE"]

    - name: Add custom address objects
      panos_address_object:
        provider:
          ip_address: "192.168.1.1"
          api_key: "YOUR_API_KEY"
        name: "{{ item.name }}"
        value: "{{ item.ip }}"
        description: "{{ item.description }}"
      loop:
        - { name: "web_server", ip: "192.168.30.10", description: "Web Server Address" }
        - { name: "db_server", ip: "192.168.40.10", description: "Database Server Address" }

    - name: Add custom service objects
      panos_service_object:
        provider:
          ip_address: "192.168.1.1"
          api_key: "YOUR_API_KEY"
        name: "{{ item.name }}"
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.port }}"
        description: "{{ item.description }}"
      loop:
        - { name: "http", protocol: "tcp", port: "80", description: "HTTP Service" }
        - { name: "https", protocol: "tcp", port: "443", description: "HTTPS Service" }
